/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazproyecto;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author pablo
 */
public class ComboSimple extends javax.swing.JFrame {
    String InicioEstadia = null;
    String combos[] = {"Combo Simple"};
    double precios[] ={60};
    double precioU = 0;
    int noche = 0;
    
    ArrayList<FacturaCarrito> ListaVenta;
    /**
     * Creates new form ComboSimple
     */
    public ComboSimple() {
        initComponents();
        this.setLocationRelativeTo(this);
        setImageLabel(Fondo_madera, "C:src\\imagen_interfaz\\madera.jpg");
        DefaultComboBoxModel ComboModel = new DefaultComboBoxModel(combos);
        ComCombos.setModel(ComboModel);
        
        ListaVenta = new ArrayList();
    }
    
    public ComboSimple(ArrayList listaVenta) {
        initComponents();
        this.setLocationRelativeTo(this);
        setImageLabel(Fondo_madera, "C:src\\imagen_interfaz\\madera.jpg");
        DefaultComboBoxModel ComboModel = new DefaultComboBoxModel(combos);
        
        ComCombos.setModel(ComboModel);
        
        ListaVenta = listaVenta;
    }
    
    public String aMoneda(double precio){
        return Math.round(precio*100.0)/100.0 + " Q";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bd = new javax.swing.JPanel();
        Hotel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        Fondo_madera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComCombos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        YearInicio = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Unitario = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        SpnNoches = new javax.swing.JSpinner();
        diasInicio = new javax.swing.JSpinner();
        MesInicio = new javax.swing.JSpinner();
        Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bd.setBackground(new java.awt.Color(0, 0, 0));
        bd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hotel.setBackground(new java.awt.Color(255, 204, 204));
        Hotel.setFont(new java.awt.Font("Vladimir Script", 0, 36)); // NOI18N
        Hotel.setForeground(new java.awt.Color(255, 255, 255));
        Hotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel.setText("Valkiria");
        Hotel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bd.add(Hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        bd.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bd.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 370, 120, 60));

        Fondo_madera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_interfaz/madera.jpg"))); // NOI18N
        Fondo_madera.setText("jLabel1");
        bd.add(Fondo_madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 750, 140));

        jLabel1.setText("jLabel1");
        bd.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 290));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("combos");
        bd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dia");
        bd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("noches");
        bd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        ComCombos.setBackground(new java.awt.Color(102, 102, 102));
        ComCombos.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.acceleratorForeground"));
        ComCombos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComCombosActionPerformed(evt);
            }
        });
        bd.add(ComCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 230, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año");
        bd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("fecha de inicio");
        bd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        YearInicio.setModel(new javax.swing.SpinnerNumberModel(2023, 2023, null, 1));
        bd.add(YearInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        bd.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 350, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        bd.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 112, 350, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mes");
        bd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio");
        bd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        Unitario.setBackground(new java.awt.Color(255, 255, 255));
        Unitario.setForeground(new java.awt.Color(255, 255, 255));
        Unitario.setText("60.0Q");
        bd.add(Unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        bd.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 350, -1));

        SpnNoches.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        SpnNoches.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpnNochesStateChanged(evt);
            }
        });
        bd.add(SpnNoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        diasInicio.setModel(new javax.swing.SpinnerNumberModel(1, null, 31, 1));
        bd.add(diasInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        MesInicio.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        bd.add(MesInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        Total.setBackground(new java.awt.Color(255, 255, 255));
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("60.0Q");
        bd.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComCombosActionPerformed
        CalcularPrecio();
    }//GEN-LAST:event_ComCombosActionPerformed

    private void SpnNochesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpnNochesStateChanged
        CalcularPrecio();
    }//GEN-LAST:event_SpnNochesStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int dia = (int) diasInicio.getValue();
    int mes = (int) MesInicio.getValue();
    int año = (int) YearInicio.getValue();
    String InicioEstadia = dia + "/" + mes + "/" + año;
        
    FacturaCarrito carrito = new FacturaCarrito();
    carrito.setId(ComCombos.getSelectedIndex());
    carrito.setCombo(ComCombos.getSelectedItem().toString());
    carrito.setInicioEstadia(InicioEstadia);
    if(noche == 0){
        noche += 1;
    }
    if(precioU == 0){
        precioU += 60;
    }
    carrito.setPrecio(precioU*noche);
    carrito.setNoches(noche);
    
    ListaVenta.add(carrito);
    
    Carrito formCarrito = new Carrito(ListaVenta);
    formCarrito.setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CalcularPrecio(){
    precioU = precios[ComCombos.getSelectedIndex()];
    noche = Integer.parseInt(SpnNoches.getValue().toString());
    Total.setText(aMoneda(precioU*noche));
    Unitario.setText(aMoneda(precioU));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboSimple().setVisible(true);
            }
        });
    }
    private void setImageLabel(JLabel labelname, String root ){
            ImageIcon image = new ImageIcon(root);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
            labelname.setIcon(icon);
            this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComCombos;
    private javax.swing.JLabel Fondo_madera;
    private javax.swing.JLabel Hotel;
    private javax.swing.JSpinner MesInicio;
    private javax.swing.JSpinner SpnNoches;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Unitario;
    private javax.swing.JSpinner YearInicio;
    private javax.swing.JPanel bd;
    private javax.swing.JSpinner diasInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
