/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazproyecto;

import java.awt.Color;

/**
 *
 * @author pablo
 */
public class Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hotel_generico = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre_text = new javax.swing.JTextField();
        DPI_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nacionalidad_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nacimiento_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correo_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contrasena_text = new javax.swing.JPasswordField();
        confirmar_text = new javax.swing.JPasswordField();
        regresoBtm = new javax.swing.JButton();
        registarseBtm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_interfaz/fondo_azul1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 220, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_interfaz/fondo_azul1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 510));

        hotel_generico.setFont(new java.awt.Font("Vladimir Script", 0, 24)); // NOI18N
        hotel_generico.setForeground(new java.awt.Color(255, 255, 255));
        hotel_generico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotel_generico.setText("Hotel Generico");
        bg.add(hotel_generico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 60));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 340, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nombre");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No.DPI");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        nombre_text.setBackground(new java.awt.Color(0, 0, 0));
        nombre_text.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        nombre_text.setForeground(new java.awt.Color(204, 204, 204));
        nombre_text.setText("ingrese su nombre completo");
        nombre_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_textMousePressed(evt);
            }
        });
        bg.add(nombre_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, -1));

        DPI_text.setBackground(new java.awt.Color(0, 0, 0));
        DPI_text.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        DPI_text.setForeground(new java.awt.Color(204, 204, 204));
        DPI_text.setText("ingrese su DPI");
        DPI_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPI_textMousePressed(evt);
            }
        });
        bg.add(DPI_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 110, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nacionalidad");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, -1));

        nacionalidad_text.setBackground(new java.awt.Color(0, 0, 0));
        nacionalidad_text.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        nacionalidad_text.setForeground(new java.awt.Color(204, 204, 204));
        nacionalidad_text.setText("ingrese su nacionalidad");
        nacionalidad_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nacionalidad_textMousePressed(evt);
            }
        });
        nacionalidad_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidad_textActionPerformed(evt);
            }
        });
        bg.add(nacionalidad_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de nacimiento");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, 20));

        nacimiento_text.setBackground(new java.awt.Color(0, 0, 0));
        nacimiento_text.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        nacimiento_text.setForeground(new java.awt.Color(204, 204, 204));
        nacimiento_text.setText("mes-año-dia");
        nacimiento_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nacimiento_textMousePressed(evt);
            }
        });
        bg.add(nacimiento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo Electronico");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 280, 20));

        correo_text.setBackground(new java.awt.Color(0, 0, 0));
        correo_text.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        correo_text.setForeground(new java.awt.Color(204, 204, 204));
        correo_text.setText("ingrese su correo electronico");
        correo_text.setToolTipText("");
        correo_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correo_textMousePressed(evt);
            }
        });
        bg.add(correo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contraseña");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 280, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ingrese de nuevo la contraseña");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, -1));

        contrasena_text.setBackground(new java.awt.Color(0, 0, 0));
        contrasena_text.setForeground(new java.awt.Color(204, 204, 204));
        contrasena_text.setText("**********");
        contrasena_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasena_textMousePressed(evt);
            }
        });
        bg.add(contrasena_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, -1));

        confirmar_text.setBackground(new java.awt.Color(0, 0, 0));
        confirmar_text.setForeground(new java.awt.Color(204, 204, 204));
        confirmar_text.setText("**********");
        confirmar_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmar_textMousePressed(evt);
            }
        });
        bg.add(confirmar_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 280, -1));

        regresoBtm.setBackground(new java.awt.Color(0, 0, 0));
        regresoBtm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_interfaz/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        regresoBtm.setBorder(null);
        regresoBtm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresoBtm.setDisabledIcon(null);
        regresoBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoBtmActionPerformed(evt);
            }
        });
        bg.add(regresoBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 60));

        registarseBtm.setBackground(new java.awt.Color(255, 153, 0));
        registarseBtm.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        registarseBtm.setForeground(new java.awt.Color(255, 255, 255));
        registarseBtm.setText("Registrarte");
        registarseBtm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registarseBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarseBtmActionPerformed(evt);
            }
        });
        bg.add(registarseBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 441, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresoBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoBtmActionPerformed
    inicioSesion abrir = new inicioSesion();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_regresoBtmActionPerformed

    private void nacionalidad_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidad_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidad_textActionPerformed

    private void nombre_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_textMousePressed
        if(nombre_text.getText().equals("ingrese su nombre completo")){
    nombre_text.setText("");
    nombre_text.setForeground(Color.white);
    }
    if(String.valueOf(DPI_text.getText()).isEmpty()){
    DPI_text.setText("ingrese su DPI");
    DPI_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_nombre_textMousePressed

    private void DPI_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPI_textMousePressed
     if( String.valueOf(DPI_text.getText()).equals("ingrese su DPI")){
    DPI_text.setText("");
    DPI_text.setForeground(Color.white);
    }
    if(nombre_text.getText().isEmpty()){
    nombre_text.setText("ingrese su nombre completo");
    nombre_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_DPI_textMousePressed

    private void nacionalidad_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nacionalidad_textMousePressed
        if(nacionalidad_text.getText().equals("ingrese su nacionalidad")){
    nacionalidad_text.setText("");
    nacionalidad_text.setForeground(Color.white);
    }
    if(String.valueOf(nacimiento_text.getText()).isEmpty()){
    nacimiento_text.setText("mes-año-dia");
    nacimiento_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_nacionalidad_textMousePressed

    private void correo_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correo_textMousePressed
    if(correo_text.getText().equals("ingrese su correo electronico")){
    correo_text.setText("");
    correo_text.setForeground(Color.white);
    }
    if(String.valueOf(nacimiento_text.getText()).isEmpty()){
    nacimiento_text.setText("mes-año-dia");
    nacimiento_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_correo_textMousePressed

    private void contrasena_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasena_textMousePressed
    char[] password = contrasena_text.getPassword();
    if (String.valueOf(password).equals("**********")) {
        contrasena_text.setText("");
        contrasena_text.setForeground(Color.white);
    }
    char[] confirmarPassword = confirmar_text.getPassword();
    if (String.valueOf(confirmarPassword).isEmpty()) {
        confirmar_text.setText("**********");
        confirmar_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_contrasena_textMousePressed

    private void confirmar_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmar_textMousePressed
    char[] confirmarPassword = confirmar_text.getPassword();
    if (String.valueOf(confirmarPassword).equals("**********")) {
        confirmar_text.setText("");
        confirmar_text.setForeground(Color.white);
    }
    char[] password = contrasena_text.getPassword();
    if (String.valueOf(password).isEmpty()) {
        contrasena_text.setText("**********");
        contrasena_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_confirmar_textMousePressed

    private void registarseBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarseBtmActionPerformed
    Seleccion abrir = new Seleccion();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_registarseBtmActionPerformed

    private void nacimiento_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nacimiento_textMousePressed
        if(nacimiento_text.getText().equals("mes-año-dia")){
            nacimiento_text.setText("");
            nacimiento_text.setForeground(Color.white);
        }
        if(String.valueOf(nacionalidad_text.getText()).isEmpty()){
            nacionalidad_text.setText("ingrese su nacionalidad");
            nacimiento_text.setForeground(Color.gray);
        }
        if(String.valueOf(correo_text.getText()).isEmpty()){
            correo_text.setText("ingrese su correo electronico");
            correo_text.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nacimiento_textMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPI_text;
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField confirmar_text;
    private javax.swing.JPasswordField contrasena_text;
    private javax.swing.JTextField correo_text;
    private javax.swing.JLabel hotel_generico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nacimiento_text;
    private javax.swing.JTextField nacionalidad_text;
    private javax.swing.JTextField nombre_text;
    private javax.swing.JButton registarseBtm;
    private javax.swing.JButton regresoBtm;
    // End of variables declaration//GEN-END:variables
}
