/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazproyecto;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import java.net.URL;
/**
 *
 * @author pablo
 */
public class inicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
        setImageLabel(fondoAzul2, "C:src\\imagen_interfaz\\fondo_azul2.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Hotel = new javax.swing.JLabel();
        CinicioSesion = new javax.swing.JLabel();
        Cusuario = new javax.swing.JLabel();
        Ccontrasena = new javax.swing.JLabel();
        usuario_text = new javax.swing.JTextField();
        SeparadorH = new javax.swing.JSeparator();
        SeparadorU = new javax.swing.JSeparator();
        SeparadorC = new javax.swing.JSeparator();
        contrasena_text = new javax.swing.JPasswordField();
        InicioSesionBtm = new javax.swing.JButton();
        RegistrarBtm = new javax.swing.JButton();
        SinCuenta = new javax.swing.JLabel();
        fondoAzul2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(102, 102, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Hotel.setBackground(new java.awt.Color(255, 204, 204));
        Hotel.setFont(new java.awt.Font("Vladimir Script", 0, 36)); // NOI18N
        Hotel.setForeground(new java.awt.Color(255, 255, 255));
        Hotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel.setText("Valkiria");
        Hotel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        CinicioSesion.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        CinicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        CinicioSesion.setText("Iniciar sesion");

        Cusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Cusuario.setForeground(new java.awt.Color(255, 255, 255));
        Cusuario.setText("Usuario");

        Ccontrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Ccontrasena.setForeground(new java.awt.Color(255, 255, 255));
        Ccontrasena.setText("constraseña");

        usuario_text.setBackground(new java.awt.Color(0, 0, 0));
        usuario_text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuario_text.setForeground(new java.awt.Color(204, 204, 204));
        usuario_text.setText("Ingrese el nombre de usuario");
        usuario_text.setBorder(null);
        usuario_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuario_textMousePressed(evt);
            }
        });

        contrasena_text.setBackground(new java.awt.Color(0, 0, 0));
        contrasena_text.setForeground(new java.awt.Color(204, 204, 204));
        contrasena_text.setText("**********");
        contrasena_text.setBorder(null);
        contrasena_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasena_textMousePressed(evt);
            }
        });

        InicioSesionBtm.setBackground(new java.awt.Color(255, 153, 0));
        InicioSesionBtm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        InicioSesionBtm.setForeground(new java.awt.Color(255, 255, 255));
        InicioSesionBtm.setText("iniciar sesión");
        InicioSesionBtm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InicioSesionBtm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InicioSesionBtm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioSesionBtmMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InicioSesionBtmMousePressed(evt);
            }
        });
        InicioSesionBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesionBtmActionPerformed(evt);
            }
        });

        RegistrarBtm.setBackground(new java.awt.Color(255, 153, 0));
        RegistrarBtm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RegistrarBtm.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarBtm.setText("Registrarte");
        RegistrarBtm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegistrarBtm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBtmActionPerformed(evt);
            }
        });

        SinCuenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SinCuenta.setForeground(new java.awt.Color(255, 255, 255));
        SinCuenta.setText("¿Aún no tienes cuenta?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(SeparadorH, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CinicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuario_text, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(SeparadorU)
                            .addComponent(SeparadorC)
                            .addComponent(contrasena_text))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InicioSesionBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SinCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegistrarBtm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CinicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InicioSesionBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SinCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegistrarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SeparadorU, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(Ccontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasena_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(SeparadorC, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 710, 360));

        fondoAzul2.setForeground(new java.awt.Color(255, 153, 0));
        fondoAzul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_interfaz/fondo_azul2.jpg"))); // NOI18N
        fondoAzul2.setText("jLabel1");
        bg.add(fondoAzul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioSesionBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioSesionBtmMouseClicked
    InicioSesionBtm.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_InicioSesionBtmMouseClicked

    private void usuario_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_textMousePressed
    if(usuario_text.getText().equals("Ingrese el nombre de usuario")){
    usuario_text.setText("");
    usuario_text.setForeground(Color.white);
    }
    if(String.valueOf(contrasena_text.getPassword()).isEmpty()){
    contrasena_text.setText("**********");
    contrasena_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_usuario_textMousePressed

    private void contrasena_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasena_textMousePressed
    if( String.valueOf(contrasena_text.getPassword()).equals("**********")){
    contrasena_text.setText("");
    contrasena_text.setForeground(Color.white);
    }
    if(usuario_text.getText().isEmpty()){
    usuario_text.setText("Ingrese el nombre de usuario");
    usuario_text.setForeground(Color.gray);
    }
    }//GEN-LAST:event_contrasena_textMousePressed

    private void InicioSesionBtmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioSesionBtmMousePressed

    }//GEN-LAST:event_InicioSesionBtmMousePressed

    private void InicioSesionBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSesionBtmActionPerformed
    Seleccion abrir = new Seleccion();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_InicioSesionBtmActionPerformed

    private void RegistrarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBtmActionPerformed
    Ingresar abrir = new Ingresar();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_RegistrarBtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSesion().setVisible(true);
            }
        });
    }
    private void setImageLabel(JLabel labelname, String root ){
            ImageIcon image = new ImageIcon(root);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
            labelname.setIcon(icon);
            this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ccontrasena;
    private javax.swing.JLabel CinicioSesion;
    private javax.swing.JLabel Cusuario;
    private javax.swing.JLabel Hotel;
    private javax.swing.JButton InicioSesionBtm;
    private javax.swing.JButton RegistrarBtm;
    private javax.swing.JSeparator SeparadorC;
    private javax.swing.JSeparator SeparadorH;
    private javax.swing.JSeparator SeparadorU;
    private javax.swing.JLabel SinCuenta;
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField contrasena_text;
    private javax.swing.JLabel fondoAzul2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuario_text;
    // End of variables declaration//GEN-END:variables

    
}

